{
  imports = [
    ./neotree.nix
    ./noice.nix
    ./notify.nix
    ./conform.nix
    ./mini.nix
    ./whichkey.nix
    ./dashboard.nix
    ./lsp.nix
    ./luasnip.nix
    ./cmp.nix
    ./fidget.nix
    ./gitsigns.nix
    ./lspsaga.nix
    ./trouble.nix
    ./nui.nix
    ./precognition.nix
    ./go-nvim.nix
    ./dap.nix
    #./ufo.nix
    ./lang
    ./treesitter/treesitter.nix
    ./treesitter/treesitter-textobjects.nix
  ];
}
