{
  imports = [
    ./alpha.nix
    ./dap.nix
    ./cmp.nix
    ./conform.nix
    ./codecompanion.nix
    ./fidget.nix
    ./flash.nix
    ./gitsigns.nix
    ./lang
    ./lsp.nix
    ./lspkind.nix
    ./lspsaga.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./minuet.nix
    ./nvim-tree.nix
    ./noice.nix
    ./notify.nix
    ./treesitter/treesitter.nix
    ./treesitter/treesitter-textobjects.nix
    ./trouble.nix
    ./ufo.nix
    ./wrapping.nix
    ./whichkey.nix
  ];
}
